using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;

/// <summary>
/// Summary description for SendEmail
/// </summary>
public class SendEmail
{
    public SendEmail()
    {
        //
        // TODO: Add constructor logic here
        //
    }

    public static void send(string VehicleName, string DriverName, string BookedBy, string Designation, string Destination, string StartTime, string EndTime)
    {
        MailMessage mail = new MailMessage();
        SmtpClient client = new SmtpClient();
        client.Port = 25;
        client.DeliveryMethod = SmtpDeliveryMethod.Network;
        client.UseDefaultCredentials = false;
        client.Host = "192.168.1.14";
        MailAddress ma = new MailAddress("Appliction Notification <AppNotification@meridianfinancebd.com>");
        mail.From =  ma ;
	//mail.To.Add("Haideruzzaman ABM <Haider@meridianfinancebd.com>");
	mail.To.Add("Manuza Begum <Manuza@meridianfinancebd.com>");
        mail.CC.Add("Afajul Ameen <Afajul@meridianfinancebd.com>");
        mail.CC.Add("Information Technology <divit@meridianfinancebd.com>");
        mail.Subject = "Vehicle Booking - New Request";
        mail.Body =

@"<!DOCTYPE html>
<html>
<head>
    <meta charset=""utf-8"" />
    <title></title>
    <style>
        * {
            font-family: Tahoma;
        }
        table {
            border-collapse: collapse;
        }
        tr, td {
            padding: 5px;
        }
        #td_font {
            font-size: small;
            color: darkgray;
        }
        #a_col {
            color: darkgray;
        }
            #a_col:hover {
                color: steelblue;
            }
    </style>
</head>
<body>
    <table>
        <tr>
            <td>
                Vehicle Name
            </td>
            <td>
                :
            </td>
            <td>
                " + VehicleName + @"
            </td>
        </tr>
        <tr>
            <td>
                Driver Name
            </td>
            <td>
                :
            </td>
            <td>
                " + DriverName + @"
            </td>
        </tr>
        <tr>
            <td>
                Booked By
            </td>
            <td>
                :
            </td>
            <td>
                <b>" + BookedBy + @"</b>
            </td>
        </tr>
        <tr>
            <td>
                Destination
            </td>
            <td>
                :
            </td>
            <td>
                " + Destination + @"
            </td>
        </tr>
        <tr>
            <td>
                Date
            </td>
            <td>
                :
            </td>
            <td>
                "+ Convert.ToDateTime(EndTime).ToString("dd MMMM yyyy") + @"
            </td>
        </tr>
        <tr>
            <td>
                Duration
            </td>
            <td>
                :
            </td>
            <td>
                " + Convert.ToDateTime(StartTime).ToString("hh:mm tt") + " - " + Convert.ToDateTime(EndTime).ToString("hh:mm tt") + @"
            </td>
        </tr>
    </table>
    <table>
        <tr>
            <td id=""td_font"">This email has been generated by Vehicle Booking Web Application (<a id=""a_col"" href=""http://webApp.mfilbd.com/VehicleBooking"">http://webApp.mfilbd.com/VehicleBooking</a>)</td>
        </tr>
    </table>
</body>
</html>
";
        mail.IsBodyHtml = true;
        client.Send(mail);
    }
}